### ISSUE TITLE
Ryzen-ppd stopped working on Arch since last week

### ISSUE THREAD

**Issue by ghost** [xsmile/ryzen-ppd#2]
Greetings,
I would like to report an error in 'ryzen-ppd', since last week or two the service fails here is the verbose output:
```
DEBUG] power_source: battery, profile: balanced, update_rate_s: 32.00, platform_profile: low-power
[DEBUG] monitored stapm_limit has changed: 25.0 != 37.0
[DEBUG] stapm_limit: 25000
[DEBUG] fast_limit: 30000
Unauthorized memory access (SIGSEGV) (core dumped [memory image saved])
```
I tried completely removing 'ryzen-ppd' and installing it back but the issue persists.

**Comment by xsmile** [comment]
Hi DunoCZ, this is an issue with the dependency python-dbus-next, see https://github.com/altdesktop/python-dbus-next/issues/138.
Until a new release is published, you can use the current version from Github or the AUR package python-dbus-next-git if this applies to you.

**Comment by ghost** [comment]
Thank you for the fast reply, yes switching from python-dbus-next to python-dbus-next-git solved the problem! Thank you! :)
